version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run:
          name: Create the test results directory
          command: mkdir -p $TEST_RESULTS
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Install go-junit-report
          command: make bin/go-junit-report
      - run:
          name: Run tests
          command: |
            trap "./bin/go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -v ./... | tee ${TEST_RESULTS}/go-test.out
      - run:
          name: Lint
          command: make lint
      - run:
          name: Build
          command: make install
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
